#!/bin/bash

set -e

EXE="$1"
OUT_DIR="$(dirname "$EXE")"

declare -A VISITED

find_dlls() {
  local file="$1"

  local dlls
  dlls=$(objdump -p "$file" 2>/dev/null \
    | awk '/DLL Name/ {print $3}')

  for dll in $dlls; do
    if [[ ${VISITED[$dll]} ]]; then
      continue
    fi
    VISITED[$dll]=1


    path=$(which "$dll" 2>/dev/null || true)

    if [ -z "$path" ]; then
      continue
    fi

    case "$path" in
      */System32*|*\\System32*)
        continue
        ;;
    esac

    cp -f "$path" "$OUT_DIR/"

    find_dlls "$path"
  done
}

find_dlls "$EXE"
